Fix Spark3 encoders for collections of Timestamp/Date (#92)
Before this fix we would get failures like
```
- encoder for scala.collection.immutable.Seq[com.choreograph.tyda.Date$package.Date] round trip *** FAILED ***
  org.apache.spark.SparkRuntimeException: Error while encoding: java.lang.RuntimeException: java.lang.Integer is not a valid external type for schema of date
mapobjects(lambdavariable(MapObject, ObjectType(class java.lang.Object), true, -1), assertnotnull(date_from_unix_date(validateexternaltype(lambdavariable(MapObject, ObjectType(class java.lang.Object), true, -1), DateType, IntegerType))), input[0, scala.collection.immutable.Seq, true], None) AS value#32.
  at org.apache.spark.sql.errors.QueryExecutionErrors$.expressionEncodingError(QueryExecutionErrors.scala:1415)
  at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:211)
```
Because we are not using the same types as Spark for Timestamp and Date.
This fix was just to fix the expected type used in ValidateExternalType.

The reason we don't run into this for Spark 4 is that this PR
https://github.com/apache/spark/pull/50023 ends up applying a fix with
the safe effect upstream.

Fixes #88

---------

Co-authored-by: dahlbaek <30782351+dahlbaek@users.noreply.github.com>