Fix `sbt tydaRepl/run`
This adds some more logic to figure out the current classpath when
starting tyda-repl. This logic is enough to make
```
sbt tydaRepl/run --runner iterator
```
but doing actual compuations will still fail as the runner will not be
on the classpath
```
scala> Dataset.from(Seq(1,2,3)).select(_ + 1).toSeq
java.lang.RuntimeException: Runner for 'Iterator' not found. Make sure that 'tyda-iterator' is on your classpath.
  at com.choreograph.tyda.RunnerArgs$.createRunner(RunnerArgs.scala:44)
  at com.choreograph.tyda.repl.TydaRepl$.initRunner(TydaRepl.scala:23)
  at rs$line$1$.runner$lzyINIT1(rs$line$1:5)
  at rs$line$1$.runner(rs$line$1:5)
  ... 45 elided
```
but I think this is unavoidable since by default the repl should have no
runner dependencies. Maybe we can add some aliases to start it with the
different runners.